export { default as HomePage } from './Home';
export { default as LoginPage } from './LoginPage';
export { default as ErrorPage } from './ErrorPage';
export { default as RegisterPage } from './RegisterPage';
export { default as StorePage } from './StorePage';
export { default as DetailProductPage } from './DetailProductPage';
export { default as ConfirmPage } from './ConfirmPage';
export { default as ResetPage } from './ResetPage';
export { default as ProductPage } from './ProductPage';