//GET PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";
export const ADD_FAIL = "ADD_FAIL";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
//GET SINGLE PRODUCTS
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";
//CART
export const CART_LOADING = "CART_LOADING";
export const CART_LOADED = "CART_LOADED";
export const ADDCART_SUCCESS = "ADDCART_SUCCESS";
export const ADDCART_FAIL = "ADDCART_FAIL";
//USER AUTHENTICATION
export const CLEAR_REGISTER_MSG = "CLEAR_REGISTER_MSG";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "USER_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//ERROR
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "GET_ERROR";