//GET PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";
//USER AUTHENTICATION
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "USER_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//ERROR
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "GET_ERROR";